[ids]

*

[main]
# Maps capslock to escape when pressed and control when held.
capslock = overload(control, esc)
# Maps left meta to alt+f1 when tapped alone
leftmeta = overload(meta, macro(A-f1))

# Makes a shift layer
[shift]
leftshift = capslock
rightshift = capslock
# i.e, when some shift is pressed down, the other shift being pressed will yield a capslock.
# So, press lshift+rshift for capslock
